# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.3

    steps:
      - checkout

      - restore_cache:
          key: dependency-cache-{{ checksum "./package.json" }}

      - run:
          name: install
          command: npm install

      - save_cache:
          key: dependency-cache-{{ checksum "./package.json" }}
          paths:
            - ./node_modules

      - run:
          name: build
          command: npm run build

      - persist_to_workspace:
            root: ./
            paths:
              - output

  deploy:
    docker:
      - image: circleci/node:8.9.3

    steps:
      - checkout

      - attach_workspace:
          at: /tmp

      - restore_cache:
          key: dependency-cache-{{ checksum "./package.json" }}

      - run:
          name: install
          command: npm install

      - save_cache:
          key: dependency-cache-{{ checksum "./package.json" }}
          paths:
            - ./node_modules

      - run:
          name: deploy-netlify
          command: ./node_modules/.bin/netlify deploy -s $NETLIFY_SITE_ID -p output -t $NETLIFY_ACCESS_TOKEN -e production

workflows:
  version: 2
  all_jobs:
    jobs:
      - build
      - deploy